### ISSUE TITLE
Generate MD5 checksum file when release.

### ISSUE THREAD

**Issue by flesire** [dcoraboeuf/ontrack#280]
Generate an MD5 when a new version is released allow user to verify that the download war file and hpi file are correct.

**Comment by dcoraboeuf** [comment]
Easy to do, but do you see that as files being downloadable from GitHub?

**Comment by dcoraboeuf** [comment]
Can you please review the attached code and tell me if that would suit you. I changed MD5 into SHA1 - the former not being recommended any longer even for the download check case.

**Comment by flesire** [comment]
It's ok for me. At least i'm able to check that the downloaded archive is the correct one.
