### ISSUE TITLE
Having a Jenkins plug-in to get build with a given property value

### ISSUE THREAD

**Issue by dcoraboeuf** [dcoraboeuf/ontrack#287]

**Comment by dcoraboeuf** [comment]
Extract an `EntityService` from methods in `ManagementService` and `EventService`.

**Comment by dcoraboeuf** [comment]
The query on property only could return a build that does not belong to the project & branch. The filtering can be achieved by looping over the build names & checking if they are actually defined for the given project & branch.

**Comment by cpf** [comment]
Needs to be reopened, bug in the jenkins plugin doesn't persist the property value (See pull request)
