### ISSUE TITLE
Allow filter in branch view to display last build for each promotion level

### ISSUE THREAD

**Issue by flesire** [dcoraboeuf/ontrack#312]
The user should be able to create a filter in branch view to get last build for each promotion level like in project view. This type of filter allow easier comparison between two promotion level.

**Comment by dcoraboeuf** [comment]
Any idea how this filter would look like in the filter dialog box?

**Comment by flesire** [comment]
I suggest following solution to dd a checkbox with label 'Keep last build per promotion'. I think this choice should disable some other choice. I can make a try and show you the result.

**Comment by dcoraboeuf** [comment]
I'm not sure to really understand what this filter is supposed to do.

**Comment by dcoraboeuf** [comment]
The idea is to have a filter that displays the last build of each promotion level.
