### ISSUE TITLE
Not possible to remove a property.

### ISSUE THREAD

**Issue by flesire** [dcoraboeuf/ontrack#319]
When a property is added (like 'jenkins url' for example), it's not possible to remove it.

**Comment by dcoraboeuf** [comment]
To remove a property, set its value to blank and validate.

**Comment by flesire** [comment]
Not working, invalid url error.
![image](https://cloud.githubusercontent.com/assets/1262565/2916161/0466c448-d6b8-11e3-8388-0e2b5302162b.png)

**Comment by dcoraboeuf** [comment]
Which version are you using? 1.48 or 1.49? See also #311. It could be a regression.

**Comment by flesire** [comment]
Version 1.49 but is it possible that this problem is a regression due to fix #311 ?

**Comment by dcoraboeuf** [comment]
Yes, it is possible. I'll have a look asap, and release a 1.49.1 version.

**Comment by flesire** [comment]
I think if found a fix. I will try it at home and I will commit it tonight.

**Comment by dcoraboeuf** [comment]
I'll do that an a 1.49.x branch (master designates now the 1.50.x and is _not_ ready for release).
