### ISSUE TITLE
Error 404 when using the breadcrumb from promotion level

### ISSUE THREAD

**Issue by cpf** [dcoraboeuf/ontrack#38]
Go to a promotion level, click the branch in the breadcrumb.

Expected url: localhost:8080/ontrack/gui/project/$projectname/branch/$branchname
Actual url: localhost:8080/ontrack/gui/branch/$projectname/$branchname

**Comment by dcoraboeuf** [comment]
Hmm, cannot reproduce at all :(

**Comment by cpf** [comment]
It seems to only occur right after creating it, and in the session following the creation. One visit to home page seems to fix it.

**Comment by cpf** [comment]
Also occurs when opening the "manage promotion levels" -> Top breadcrumb doesn't always contain the correct link.
